// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
window.$ = window.jQuery = require('jquery');

import FillTotalValueController from "./fill_total_value_controller"
application.register("fill_total_value_controller", FillTotalValueController)

import MaskInput from "./mask_input"
application.register("mask_input", MaskInput)

import navBarMobileController from "./navbar_mobile_controller"
application.register("navbar_mobile", navBarMobileController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)
